@hostname = http://localhost
# @hostname = http://ec2-34-229-201-239.compute-1.amazonaws.com
@port = 9000
@host = {{hostname}}:{{port}}
@contentType = application/json

### Users

GET {{host}}/user/612cfef87de53054f2b355d6

###

POST {{host}}/user
Content-Type: {{contentType}}

{
  "name": "Jonathan L. M. Diniz",
  "username": "joanthan",
  "password": "1234",
  "pantryName": "Despensa 1",
  "pantryId": "9168b6a7-96de-45bc-a788-8a10f861adbc"
}

###

PUT {{host}}/user/612cfef87de53054f2b355d6
Content-Type: {{contentType}}

{
  "name": "Jonathan Diniz",
  "pantryName": "Despensa 2",
  "pantryId": "9168b6a7-96de-45bc-a788-8a10f861adbc"
}

###

DELETE  {{host}}/user/612cfef87de53054f2b355d6

###


GET {{host}}/pantry/add-item/7894900700046/612d00ebc726a9aa7f570f2b

### Pantry

GET {{host}}/pantry

###

POST {{host}}/pantry
Content-Type: {{contentType}}

{
  "name": "Teste",
  "pantryHash": "JDJhJDA5JGpYSnBtMnR2LzRyOE5DQVBMdnRVei5NMlo1Nzl5amRCN0lHYmxGNWNNUlRYaXV4TnFldDBH",
  "userId": "613da818635f5be40cc48d41"
}

###

GET {{host}}/pantry/items/613da818635f5be40cc48d41
Content-Type: {{contentType}}



###

PUT {{host}}/pantry/item-quantity
Content-Type: {{contentType}}

{
  "pantryId": "6150d0bf4988df1e2ae7cd10",
  "barcode": "7894900011159",
  "quantity": 10
}

###

DELETE {{host}}/pantry/delete-item/6150d0bf4988df1e2ae7cd10/7894900011159
Content-Type: {{contentType}}

### Login

POST {{host}}/sessions/login
Content-Type: {{contentType}}

{
  "username": "jonathan2",
  "password": "1234"
}